name: deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pyodide/pyodide:0.20.0

    steps:
    - uses: actions/checkout@v3

    - uses: actions/checkout@v3
      with:
        repository: AcademySoftwareFoundation/OpenTimelineIO
        path: otio-repo
        submodules: 'recursive'

    - name: Create sdist
      run: |
        python -m pip install build
        python -m build -s --outdir . otio-repo

    - name: Prepare environment
      run: |
        echo $(pwd)
        ls -la
        cd /src/pyodide
        make

    - name: Build wasm wheel
      run: ./build.sh $(pwd)
