name: deploy

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone OpenTimelineIO
      uses: actions/checkout@v3
      with:
        repository: AcademySoftwareFoundation/OpenTimelineIO
        path: OpenTimelineIO
        submodules: 'recursive'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: mymindstorm/setup-emsdk@v11
      with:
        version: '3.1.14'

    - run: pip install pyodide-build==0.21.0

    - run: git apply < ../patch.patch
      working-directory: OpenTimelineIO

    - run: pyodide build --exports pyinit
      working-directory: OpenTimelineIO
      env:
        VERBOSE: '1'
        OTIO_CXX_BUILD_TYPE: RelWithDebInfo

    - uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: OpenTimelineIO/dist/*.whl

  publish:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: wheel
        path: public

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
