name: deploy

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clone OpenTimelineIO
      uses: actions/checkout@v4
      with:
        repository: JeanChristopheMorinPerso/OpenTimelineIO
        ref: switch_to_scikit_build_core
        path: OpenTimelineIO
        submodules: 'recursive'

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - uses: pypa/cibuildwheel@v2.20.0
      with:
        package-dir: OpenTimelineIO
        output-dir: dist
      env:
        CIBW_PLATFORM: pyodide
        # whole_archive is needed to make all symbols available.
        CIBW_BUILD_FRONTEND: 'build; args: --exports=whole_archive'
        # Note that -fwasm-exceptions doesn't work right now. It'll cause
        # a bunch of issues with symbols not found. Quite weird.
        CIBW_ENVIRONMENT: LDFLAGS="-fexceptions" CXXFLAGS="-fexceptions"

    - uses: actions/upload-artifact@v4
      name: Upload wheel artifact
      with:
        name: wheel
        path: dist/*.whl

    - name: Generate HTML
      run: |
        set -ex
        python -m pip install packaging jinja2
        python generateHtml.py dist/*.whl pages

        cp dist/*.whl pages/
        find public -mindepth 1 -not -name "*.in" -exec cp -v {} pages/ \;

    - name: Upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages

  deploy:
    needs: ['build']

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
