name: deploy

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pyodide/pyodide:0.20.0
      volumes:
      - ${{ github.workspace }}:/src/otio-wasm

    steps:
    - uses: actions/checkout@v3
      with:
        path: /src/otio-wasm

    - run: |
        cd /src/pyodide
        make

    - run: /src/otio-wasm/build.sh
